### ISSUE TITLE
Package version incompatibility

### ISSUE THREAD

**Issue by anjanatiha** [CogComp/TAWT#1]
Numpy package version listed in requirement.txt seem not to align with the requirements of other package versions listed here.

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/22654200/173908692-fc87dfee-ddc4-42a3-9efd-082110aa6e72.png">

**Comment by HornHehhf** [comment]
Thanks, Anjana! The numpy version is updated.

**Comment by anjanatiha** [comment]
Thanks

**Comment by anjanatiha** [comment]
After changing numpy to 1.19.2 compatibility issue got resolved (as tensorflow 2.5.0 depends on this version or greater of numpy), currently its set to 1.18, could you please check again?

**Comment by HornHehhf** [comment]
Hi Anjana, I already changed the numpy version to 1.19.2.  When I look at the requirement.txt, it looks as follows:
transformers==2.8.0
tqdm==4.43.0
scipy==1.4.1
seqeval==0.0.12
**numpy==1.19.2**
torch==1.4.0
apex==0.9.10dev
ptvsd==4.3.2
scikit_learn==0.24.2
tensorboardX==2.2
tensorflow==2.5.0

I'm not sure why you mean that it's currently set to 1.18. Maybe you can refresh the website and look at it again.
Thanks,
Hangfeng

**Comment by anjanatiha** [comment]
Got it.
